[package]
name = "flighty"
version = "0.1.0"
authors = ["tstellanova <tstellanova@users.noreply.github.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.17.2"
#nphysics3d = "0.10.3"

[dev-dependencies]
assert_approx_eq = "1.1.0"
rand = "0.6.5"
quickcheck = "0.6"



[dependencies.sensulator]
#git = "https://github.com/tstellanova/sensulator.git"
path = "../sensulator"

[dependencies.num]
version = "0.2"
default-features = false